pymeasure/pyleco

pyleco/core/__init__.py, pyleco/core/internal_protocols.py, pyleco/core/leco_protocols.py, pyleco/core/message.py, pyleco/core/protocols.py, pyleco/core/rpc_generator.py, pyleco/core/serialization.py, pyleco/errors.py, pyleco/test.py, pyproject.toml, tests/core/test_message.py, tests/core/test_serialization.py, tests/test_import.py
In this PR I add essential elements for further pyleco modules.
I ask you to look at `Message`, which is a real important for all the other things, and at `protocols.py` which contains the API definitions (which I will propose in LECO as commands, different Components have to offer).
Content:
- `rpc_generator` contains a helper class to generate json rpc calls and to interpret the response.
- `protocols` contains class stubs defining what a Component has to offer, or what a `Communicator` has to offer. Communicator is a pyleco tool, which a software (e.g. a GUI) may use to send and receive LECO messages. For example the Directors require a Communicator.
- `message` contains the omnipotent `Message`
- `serialization` contains helper classes to (de)serialize data, could be included in …
=> Core elements added.

.github/workflows/pyleco_CI.yml, README.md
Add a coverage badge to the readme file.
Note regarding implementation:
- That is the workflow of the coverage report: https://github.com/MishaKav/pytest-coverage-comment/blob/main/.github/workflows/live-test.yml
- https://github.com/marketplace/actions/dynamic-badges describes how to prepare everything for a dynamic badge (this is the dependency of pytest-coverage-comment): create a gist, make it public, create a secret for that gist, add it to the repository
- adjust the first script with the information of the second: gist id, file_name, secret name
- Important: You have to use the "githubusercontent" URL to work, see https://github.com/badges/shields/discussions/7435?sort=top
=> Add coverage badge

.github/workflows/pyleco_CI.yml
see #25 
now from the repo internally.
This PR adds write permission to contents, in order to write a coverage comment after a merge.
=> Fix ci, internal REPO

.github/workflows/python-publish.yml
Add a workflow to upload a release to PyPI once it is published.
It requires to [add a publisher](https://docs.pypi.org/trusted-publishers/adding-a-publisher/) to PyPI, which seems to be the most recent authentication scheme.
@bilderbuchi , could you either add me (https://pypi.org/user/bburger/) as a maintainer to pyleco on pypi, or setup pypi to accept releases from github? This is simply to enter the owner name, the repo name, the file name ("python-publish.yml") and the environment name (not applicable yet).
That will make releases quite simple: Create changelog, make a github release, done.
=> Add uploading CI workflow

pyleco/core/internal_protocols.py, pyleco/directors/director.py, pyleco/utils/communicator.py, pyleco/utils/coordinator_utils.py, pyleco/utils/pipe_handler.py, tests/core/test_internal_protocols.py, tests/directors/test_director.py, tests/utils/test_communicator.py
The `interpret_rpc_response` of the CommunicatorProtocol and the `read_rpc_response` of the Director are quality of life improvements, which skip the step of calling objects of other objects.
Additionally removal of some older code.
=> Improve communicator and director

pyleco/management/data_logger.py, tests/management/test_data_logger.py
The DataLogger did not start a new timer, if it is not specified explicitly.
A test verifies the behavior and passes with this fix.
=> Fix DataLogger to start a timer, even if not specified explicitly.

CHANGELOG.md, GETTING_STARTED.md, README.md, pyproject.toml
This allows to easily start the main infrastructure without need to locate the files in the python installation.
=> Add coordinators and starter as executable scripts

pyleco/utils/base_communicator.py, pyleco/utils/message_handler.py, pyleco/utils/pipe_handler.py, pyleco/utils/qt_listener.py, tests/utils/test_base_communicator.py, tests/utils/test_communicator.py, tests/utils/test_message_handler.py, tests/utils/test_qt_listener.py
A bug in the BaseCommunicator prevented the message handler from receiving not signed in messages and other error messages.
This PR fixes the communication.
=> Fix message handler

CHANGELOG.md, pyleco/coordinators/coordinator.py, pyleco/core/serialization.py, pyleco/utils/message_handler.py, tests/coordinators/test_coordinator.py, tests/core/test_serialization.py, tests/utils/test_message_handler.py
closes #57  and also closes #56
=> Fix coordinator

.github/workflows/pyleco_CI.yml, CHANGELOG.md, GETTING_STARTED.md, environment.yml, examples/pymeasure_actor.py, pyleco/actors/actor.py, pyleco/directors/transparent_director.py, pyleco/json_utils/rpc_server.py, pyleco/management/test_tasks/test_task.py, pyproject.toml, tests/actors/test_actor.py, tests/directors/test_transparent_director.py, tests/json_utils/test_rpc_server.py, tests/utils/test_message_handler.py
Allow Python 3.8 (previously only Python>=3.9)
- uses #63 
Main changes:
- for python<3.9 use self written `RPCServer` instead of `openrpc`.
- Rename `cls` for `TransparentDirector` and `Actor` to `device_class`, as Python 3.8 does not like `cls` in an init.
=> Old python

CHANGELOG.md, pyleco/coordinators/coordinator.py, pyleco/json_utils/errors.py, pyleco/json_utils/json_objects.py, pyleco/json_utils/rpc_generator.py, pyleco/json_utils/rpc_server_definition.py, pyleco/utils/base_communicator.py, pyleco/utils/communicator.py, pyleco/utils/coordinator_utils.py, tests/coordinators/test_coordinator.py, tests/json_utils/test_errors.py, tests/json_utils/test_json_objects.py, tests/json_utils/test_rpc_generator.py, tests/utils/test_base_communicator.py, tests/utils/test_communicator.py, tests/utils/test_coordinator_utils.py, tests/utils/test_message_handler.py
Now that we have our own json-objects and errors file, we can put all errors (even the LECO ones and the pyleco `INVALID_SERVER_RESPONSE`) into one file instead of keeping errors distributed over several files (errors, json_utils.errors, rpc_generator).
=> Reorganize json objects

pyleco/utils/listener.py, pyleco/utils/pipe_handler.py, tests/utils/test_listener.py, tests/utils/test_pipe_handler.py
=> Stopping listener closes handler which closes communicators

pyleco/coordinators/coordinator.py, tests/coordinators/test_coordinator.py
Coordinator did turn the full hostname (including periods, for example "hostname.domain.tld") into the namespace.
A namespace must not contain periods.
This PR adds tests (which failed even where `gethostname` returns just the last name) and a fix covered by these tests.
=> Fix Coordinator to not use period in hostname as namespace

pyleco/management/data_logger.py, tests/management/test_data_logger.py
Fixes bugs:
- If you set the trigger to the timer and a timeout, the timer is started before the timeout value is updated, therefore the timer uses the previous timeout value.
- There was no lock around the lists, therefore, while saving a file, the timed trigger (executed in another thread) could add elements to list, enlarging some of the lists, but not all.
This PR modifies the tests to show this scenario (first issue) and fixes the problem.
=> Fix data_logger timer

environment.yml, pyleco/core/serialization.py, pyproject.toml, tests/core/test_serialization.py
Closes #74 
I just added the (failing) test.
Implementation has to be searched for.
=> Rework UUIDv7 generation for conversation_id

CHANGELOG.md, pyleco/core/data_message.py, pyleco/core/internal_protocols.py, pyleco/core/leco_protocols.py, pyleco/core/message.py, pyleco/directors/director.py, pyleco/management/test_tasks/test_task.py, pyleco/test.py, pyleco/utils/data_publisher.py, pyleco/utils/listener.py, pyleco/utils/message_handler.py, tests/acceptance_tests/test_director_actor.py, tests/core/test_data_message.py, tests/core/test_internal_protocols.py, tests/core/test_message.py, tests/directors/test_director.py, tests/utils/test_data_publisher.py, tests/utils/test_message_handler.py
Implements the transport of binary data in additional frames, related to _How to transmit binary data_ (https://github.com/pymeasure/leco-protocol/issues/65).
Idea:
- First payload frame is JSON
- Second (and more) frame are binary
Implementation ideas.
- `MessageHandler` offers the whole message for the rpc handler and adds the additional frames afterwards
- Communicator can return the bytes
- Communicator (and Director) can send bytes in a rpc request
Open questions:
A return value of `None` with additional payload frames is a strong indicator, but not exclusive to this scenario. Is it sufficient?
=> Add binary payload handling to PyLECO

pyleco/actors/actor.py, pyleco/actors/locking_actor.py, pyleco/directors/locking_director.py, tests/actors/test_actor.py, tests/actors/test_locking_actor.py, tests/directors/test_locking_director.py, tests/management/test_starter.py
Closes #39 
Uses the message added in #82 (adaptations needed, once that is merged!)
=> Add locking actor

.github/workflows/pyleco_CI.yml
Updates ruff action to maintained version, see #92  as currently used one is not maintained anymore.
Maybe fixes the broken dependency on most current ruff, #92.
=> Fix ruff action

pyleco/json_utils/json_objects.py, pyleco/json_utils/rpc_server_definition.py, tests/json_utils/test_json_objects.py, tests/json_utils/test_rpc_server.py
Some ideas from #100 and preparation for expansion.
=> Rework rpc server

.github/workflows/pyleco_CI.yml
With the new ruff action, also a new ruff version is needed, which requires a new configuration.
=> Update ruff configuration for pipeline
